'use strict';

const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } = require('docx');
const { formatTimestamp, formatDuration, speakerName, summaryToPlainSections } = require('./shared');

async function build(meeting) {
  const children = [];

  children.push(new Paragraph({ text: meeting.title, heading: HeadingLevel.TITLE }));
  children.push(new Paragraph({
    children: [new TextRun({ text: `${new Date(meeting.created_at).toLocaleString()}  •  ${formatDuration(meeting.duration_ms)}${meeting.tags.length ? `  •  ${meeting.tags.map((t) => t.name).join(', ')}` : ''}`, color: '57606A', size: 20 })],
    spacing: { after: 300 },
  }));

  const summarySections = summaryToPlainSections(meeting.summary);
  if (summarySections.length) {
    children.push(new Paragraph({ text: 'Summary', heading: HeadingLevel.HEADING_1 }));
    if (meeting.summary?.source) {
      children.push(new Paragraph({
        children: [new TextRun({ text: `Generated by ${meeting.summary.source === 'heuristic' ? 'the built-in heuristic summarizer' : meeting.summary.source}${meeting.summary.model ? ` (${meeting.summary.model})` : ''}`, italics: true, color: '8B949E', size: 18 })],
      }));
    }
    for (const section of summarySections) {
      children.push(new Paragraph({ text: section.title, heading: HeadingLevel.HEADING_2, spacing: { before: 200 } }));
      if (section.body) children.push(new Paragraph({ text: section.body }));
      if (section.list) {
        section.list.forEach((item) => children.push(new Paragraph({ text: item, bullet: { level: 0 } })));
      }
    }
  }

  children.push(new Paragraph({ text: 'Transcript', heading: HeadingLevel.HEADING_1, spacing: { before: 300 } }));

  for (const seg of meeting.segments) {
    children.push(new Paragraph({
      spacing: { before: seg.paragraph_break ? 200 : 60 },
      children: [
        new TextRun({ text: `[${formatTimestamp(seg.start_ms)}] `, color: '8B949E' }),
        new TextRun({ text: `${speakerName(meeting, seg.speaker_id)}: `, bold: true }),
        new TextRun({ text: seg.text }),
      ],
    }));
  }

  const doc = new Document({
    sections: [{ properties: {}, children }],
    styles: { default: { document: { run: { font: 'Calibri', size: 22 } } } },
  });

  return Packer.toBuffer(doc);
}

module.exports = { build, extension: 'docx', mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', isAsync: true, isBinary: true };
