'use strict';

const { formatTimestamp, formatDuration, speakerName, htmlEscape, summaryToPlainSections } = require('./shared');

function build(meeting) {
  const summarySections = summaryToPlainSections(meeting.summary);

  const summaryHtml = summarySections.length ? `
    <section class="summary">
      <h2>Summary</h2>
      ${meeting.summary?.source ? `<p class="source-note">Generated by ${meeting.summary.source === 'heuristic' ? 'the built-in heuristic summarizer' : htmlEscape(meeting.summary.source)}${meeting.summary.model ? ` (${htmlEscape(meeting.summary.model)})` : ''}</p>` : ''}
      ${summarySections.map((s) => `
        <div class="summary-section">
          <h3>${htmlEscape(s.title)}</h3>
          ${s.body ? `<p>${htmlEscape(s.body)}</p>` : ''}
          ${s.list ? `<ul>${s.list.map((item) => `<li>${htmlEscape(item)}</li>`).join('')}</ul>` : ''}
        </div>
      `).join('')}
    </section>
  ` : '';

  const transcriptHtml = meeting.segments.map((seg) => `
    <div class="segment${seg.paragraph_break ? ' paragraph-break' : ''}">
      <span class="timestamp">${formatTimestamp(seg.start_ms)}</span>
      <span class="speaker" style="color:${resolveSpeakerColor(meeting, seg.speaker_id)}">${htmlEscape(speakerName(meeting, seg.speaker_id))}</span>
      <span class="text">${htmlEscape(seg.text)}</span>
    </div>
  `).join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>${htmlEscape(meeting.title)}</title>
<style>
  body { font-family: -apple-system, "Segoe UI", Roboto, Arial, sans-serif; color: #1c2128; max-width: 860px; margin: 40px auto; padding: 0 24px; line-height: 1.55; }
  h1 { font-size: 26px; margin-bottom: 4px; }
  .meta { color: #57606a; font-size: 14px; margin-bottom: 28px; }
  .meta span { margin-right: 16px; }
  h2 { font-size: 19px; border-bottom: 1px solid #d0d7de; padding-bottom: 6px; margin-top: 36px; }
  h3 { font-size: 15px; margin-bottom: 6px; color: #24292f; }
  .summary-section { margin-bottom: 18px; }
  .source-note { font-size: 12px; color: #8b949e; font-style: italic; }
  .segment { display: flex; gap: 12px; padding: 6px 0; font-size: 14px; }
  .segment.paragraph-break { margin-top: 16px; }
  .timestamp { color: #8b949e; font-variant-numeric: tabular-nums; flex-shrink: 0; width: 64px; }
  .speaker { font-weight: 600; flex-shrink: 0; width: 140px; }
  .text { flex: 1; }
  ul { margin: 4px 0; padding-left: 20px; }
  @media print { body { margin: 0; padding: 24px; } }
</style>
</head>
<body>
  <h1>${htmlEscape(meeting.title)}</h1>
  <div class="meta">
    <span>${new Date(meeting.created_at).toLocaleString()}</span>
    <span>${formatDuration(meeting.duration_ms)}</span>
    ${meeting.tags.length ? `<span>${meeting.tags.map((t) => htmlEscape(t.name)).join(', ')}</span>` : ''}
  </div>
  ${summaryHtml}
  <h2>Transcript</h2>
  ${transcriptHtml}
</body>
</html>`;
}

function resolveSpeakerColor(meeting, speakerId) {
  const speaker = meeting.speakers.find((s) => s.id === speakerId);
  return speaker ? speaker.color : '#57606a';
}

module.exports = { build, extension: 'html', mimeType: 'text/html' };
