'use strict';

const { formatTimestamp, formatDuration, speakerName, summaryToPlainSections } = require('./shared');

function build(meeting) {
  const lines = [];
  lines.push(`# ${meeting.title}`);
  lines.push('');
  lines.push(`**Date:** ${new Date(meeting.created_at).toLocaleString()}  `);
  lines.push(`**Duration:** ${formatDuration(meeting.duration_ms)}  `);
  if (meeting.tags.length) lines.push(`**Tags:** ${meeting.tags.map((t) => `\`${t.name}\``).join(' ')}  `);
  lines.push('');

  const summarySections = summaryToPlainSections(meeting.summary);
  if (summarySections.length) {
    lines.push('## Summary');
    if (meeting.summary?.source) lines.push(`*Generated by: ${meeting.summary.source === 'heuristic' ? 'built-in heuristic summarizer' : meeting.summary.source}${meeting.summary.model ? ` (${meeting.summary.model})` : ''}*`);
    lines.push('');
    for (const section of summarySections) {
      lines.push(`### ${section.title}`);
      if (section.body) lines.push(section.body);
      if (section.list) section.list.forEach((item) => lines.push(`- ${item}`));
      lines.push('');
    }
  }

  lines.push('## Transcript');
  lines.push('');
  for (const seg of meeting.segments) {
    if (seg.paragraph_break) lines.push('');
    lines.push(`**[${formatTimestamp(seg.start_ms)}] ${speakerName(meeting, seg.speaker_id)}:** ${seg.text}`);
    lines.push('');
  }

  return lines.join('\n');
}

module.exports = { build, extension: 'md', mimeType: 'text/markdown' };
